<?php
/**
 * Declarative routes (method + path + middleware).
 * Unmatched URLs fall back to legacy Dispatch (ClassRoutes + dynamic methods).
 *
 * Path params: {id}, {entityType}, etc.
 * Middleware: auth, csrf, can:permission.name, admin, super_admin
 */
return [
    // --- Home (página inicial) ---
    [
        'path' => '',
        'controller' => 'ControllerHome',
        'action' => 'index',
        'methods' => ['GET'],
    ],
    [
        'path' => 'home',
        'controller' => 'ControllerHome',
        'action' => 'index',
        'methods' => ['GET'],
    ],

    // --- Legal (páginas públicas) ---
    [
        'path' => 'cookies',
        'controller' => 'ControllerLegal',
        'action' => 'cookies',
        'methods' => ['GET'],
    ],
    [
        'path' => 'privacidade',
        'controller' => 'ControllerLegal',
        'action' => 'privacidade',
        'methods' => ['GET'],
    ],
    [
        'path' => 'termos',
        'controller' => 'ControllerLegal',
        'action' => 'termos',
        'methods' => ['GET'],
    ],

    // --- Sitemap e robots ---
    [
        'path' => 'sitemap',
        'controller' => 'ControllerSitemap',
        'action' => 'index',
        'methods' => ['GET'],
    ],
    [
        'path' => 'sitemap/pages',
        'controller' => 'ControllerSitemap',
        'action' => 'pages',
        'methods' => ['GET'],
    ],
    [
        'path' => 'sitemap/properties',
        'controller' => 'ControllerSitemap',
        'action' => 'properties',
        'methods' => ['GET'],
    ],
    [
        'path' => 'robots.txt',
        'controller' => 'ControllerSitemap',
        'action' => 'robots',
        'methods' => ['GET'],
    ],

    // --- Ficheiros protegidos ---
    [
        'path' => 'file/serve',
        'controller' => 'ControllerFile',
        'action' => 'serve',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],

    // --- API ---
    [
        'path' => 'api',
        'controller' => 'ControllerApiPages',
        'action' => 'index',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/health',
        'controller' => 'ControllerApiPages',
        'action' => 'health',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1',
        'controller' => 'ControllerApiV1',
        'action' => 'root',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1/properties',
        'controller' => 'ControllerApiV1Properties',
        'action' => 'properties',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1/property/{id}',
        'controller' => 'ControllerApiV1Properties',
        'action' => 'property',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1/tokens',
        'controller' => 'ControllerApiV1Tokens',
        'action' => 'list',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1/tokens',
        'controller' => 'ControllerApiV1Tokens',
        'action' => 'create',
        'methods' => ['POST'],
    ],
    [
        'path' => 'api/v1/tokens/{id}',
        'controller' => 'ControllerApiV1Tokens',
        'action' => 'revoke',
        'methods' => ['DELETE'],
    ],
    [
        'path' => 'api/v1/saved_searches',
        'controller' => 'ControllerApiV1SavedSearches',
        'action' => 'list',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1/saved_searches',
        'controller' => 'ControllerApiV1SavedSearches',
        'action' => 'create',
        'methods' => ['POST'],
    ],
    [
        'path' => 'api/v1/saved_searches/{id}',
        'controller' => 'ControllerApiV1SavedSearches',
        'action' => 'delete',
        'methods' => ['DELETE'],
    ],
    [
        'path' => 'api/v1/notifications/archive',
        'controller' => 'ControllerApiV1Notifications',
        'action' => 'archive',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1/notifications',
        'controller' => 'ControllerApiV1Notifications',
        'action' => 'inbox',
        'methods' => ['GET'],
    ],
    [
        'path' => 'api/v1/notifications',
        'controller' => 'ControllerApiV1Notifications',
        'action' => 'mutate',
        'methods' => ['POST'],
    ],
    [
        'path' => 'api/v1/notifications/{id}',
        'controller' => 'ControllerApiV1Notifications',
        'action' => 'delete',
        'methods' => ['DELETE'],
    ],

    // --- Legacy alias: /favorites → favoritos no painel ---
    [
        'path' => 'favorites',
        'controller' => 'ControllerDashboardHome',
        'action' => 'myFavorites',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],

    // --- Auth (ControllerAuth*) ---
    [
        'path' => 'login',
        'controller' => 'ControllerAuthPages',
        'action' => 'login',
        'methods' => ['GET'],
    ],
    [
        'path' => 'register',
        'controller' => 'ControllerAuthPages',
        'action' => 'register',
        'methods' => ['GET'],
    ],
    [
        'path' => 'authenticate',
        'controller' => 'ControllerAuthSession',
        'action' => 'authenticate',
        'methods' => ['POST'],
        'middleware' => ['csrf'],
    ],
    [
        'path' => 'store',
        'controller' => 'ControllerAuthRegistration',
        'action' => 'store',
        'methods' => ['POST'],
        'middleware' => ['csrf'],
    ],
    [
        'path' => 'verify',
        'controller' => 'ControllerAuthRegistration',
        'action' => 'verify',
        'methods' => ['GET'],
    ],
    [
        'path' => 'logout',
        'controller' => 'ControllerAuthSession',
        'action' => 'logout',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'recover',
        'controller' => 'ControllerAuthPassword',
        'action' => 'recover',
        'methods' => ['GET', 'POST'],
        'middleware' => ['csrf'],
    ],
    [
        'path' => 'reset',
        'controller' => 'ControllerAuthPassword',
        'action' => 'reset',
        'methods' => ['GET', 'POST'],
        'middleware' => ['csrf'],
    ],

    // --- Dashboard: páginas GET ---
    [
        'path' => 'dashboard',
        'controller' => 'ControllerDashboardHome',
        'action' => 'dashboard',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/myFavorites',
        'controller' => 'ControllerDashboardHome',
        'action' => 'myFavorites',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'profile',
        'controller' => 'ControllerDashboardProfile',
        'action' => 'profile',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/accountStatus',
        'controller' => 'ControllerDashboardProfile',
        'action' => 'accountStatus',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/getPromoterTerms',
        'controller' => 'ControllerDashboardProfile',
        'action' => 'getPromoterTerms',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/afiliados',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'afiliados',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/myProperties',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'myProperties',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/commissions',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'commissions',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'commissions',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'commissions',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/promotor',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'promotor',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/referrals',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'referrals',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'referrals',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'referrals',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/myAffiliates',
        'controller' => 'ControllerDashboardAffiliate',
        'action' => 'myAffiliates',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/requests',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requests',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'requests',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requests',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/requestChats',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requestChats',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/requestChatSummariesFeed',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requestChatSummariesFeed',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/disputes',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'disputes',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/requestChat/{id}',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requestChat',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/requestChatFeed/{id}',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requestChatFeed',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/requestChatMarkRead/{id}',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requestChatMarkRead',
        'methods' => ['POST'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/requestChatMarkUnread/{id}',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'requestChatMarkUnread',
        'methods' => ['POST'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/dispute/{id}',
        'controller' => 'ControllerDashboardRequests',
        'action' => 'dispute',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/payments',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'payments',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/commissionPayments',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'commissionPayments',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/commissionPayment/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'commissionPayment',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/paymentAccounts',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'paymentAccounts',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'payment_accounts',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'paymentAccounts',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/paymentHistory',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'paymentHistory',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/exportPaymentHistoryCsv',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'exportPaymentHistoryCsv',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/exportPaymentHistoryPdf',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'exportPaymentHistoryPdf',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/exportPaymentsHistoryCsv',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'exportPaymentsHistoryCsv',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/exportPaymentsHistoryPdf',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'exportPaymentsHistoryPdf',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/moderateUsers',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'moderateUsers',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:users.review'],
    ],
    [
        'path' => 'dashboard/subscription',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'subscription',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/subscriptionCheckout',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'subscriptionCheckout',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'dashboard/adminSubscriptions',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'adminSubscriptions',
        'methods' => ['GET'],
        'middleware' => ['auth', 'super_admin'],
    ],
    [
        'path' => 'admin_subscriptions',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'adminSubscriptions',
        'methods' => ['GET'],
        'middleware' => ['auth', 'super_admin'],
    ],
    [
        'path' => 'dashboard/adminSubscriptionCheckout',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'adminSubscriptionCheckout',
        'methods' => ['GET'],
        'middleware' => ['auth', 'super_admin'],
    ],
    [
        'path' => 'dashboard/auditLog',
        'controller' => 'ControllerDashboardAdmin',
        'action' => 'auditLog',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:audit.view'],
    ],
    [
        'path' => 'dashboard/auditLog/{entityType}/{entityId}',
        'controller' => 'ControllerDashboardAdmin',
        'action' => 'auditLog',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:audit.view'],
    ],
    [
        'path' => 'dashboard/kpi',
        'controller' => 'ControllerDashboardAdmin',
        'action' => 'kpi',
        'methods' => ['GET'],
        'middleware' => ['auth', 'super_admin'],
    ],
    [
        'path' => 'dashboard/propertyReports',
        'controller' => 'ControllerDashboardAdmin',
        'action' => 'propertyReports',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'settings',
        'controller' => 'ControllerDashboardAdmin',
        'action' => 'settings',
        'methods' => ['GET'],
        'middleware' => ['auth', 'super_admin'],
    ],

    // --- Dashboard: notificações (ControllerDashboardNotifications) ---
    [
        'path' => 'dashboard/markNotificationsRead',
        'controller' => 'ControllerDashboardNotifications',
        'action' => 'markNotificationsRead',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/markNotificationRead/{id}',
        'controller' => 'ControllerDashboardNotifications',
        'action' => 'markNotificationRead',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/markNotificationUnread/{id}',
        'controller' => 'ControllerDashboardNotifications',
        'action' => 'markNotificationUnread',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/notificationsFeed',
        'controller' => 'ControllerDashboardNotifications',
        'action' => 'notificationsFeed',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],

    // --- Dashboard: financeiro (ControllerDashboardPayments) ---
    [
        'path' => 'dashboard/confirmPayment/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'confirmPayment',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'dashboard/cancelPayment/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'cancelPayment',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'dashboard/rejectCommissionOwnerPayment/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'rejectCommissionOwnerPayment',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'dashboard/confirmAffiliatePayout/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'confirmAffiliatePayout',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'dashboard/submitCommissionPayment/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'submitCommissionPayment',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/addPaymentAccount',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'addPaymentAccount',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/setDefaultPaymentAccount/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'setDefaultPaymentAccount',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/deactivatePaymentAccount/{id}',
        'controller' => 'ControllerDashboardPayments',
        'action' => 'deactivatePaymentAccount',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],

    // --- Dashboard: moderação (ControllerDashboardModeration) ---
    [
        'path' => 'dashboard/moderate_users',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'moderateUsers',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:users.review'],
    ],
    [
        'path' => 'dashboard/blockUserAccess/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'blockUserAccess',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/unblockUserAccess/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'unblockUserAccess',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/suspendUserAccess/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'suspendUserAccess',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/unsuspendUserAccess/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'unsuspendUserAccess',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/setAdminRole/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'setAdminRole',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/createAdministrativeUser',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'createAdministrativeUser',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/revokeAdministrativeAccess/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'revokeAdministrativeAccess',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/suspendAdministrativeAccess/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'suspendAdministrativeAccess',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/unsuspendAdministrativeAccess/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'unsuspendAdministrativeAccess',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/approveUser/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'approveUser',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:users.review'],
    ],
    [
        'path' => 'dashboard/rejectUser/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'rejectUser',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:users.review'],
    ],

    // --- Dashboard: trust badge ---
    [
        'path' => 'dashboard/requestTrustedBadge',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'requestTrustedBadge',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/approveTrustedBadge/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'approveTrustedBadge',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:users.review'],
    ],
    [
        'path' => 'dashboard/rejectTrustedBadge/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'rejectTrustedBadge',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:users.review'],
    ],
    [
        'path' => 'dashboard/confirmTrustedBadgePayment/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'confirmTrustedBadgePayment',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],

    // --- Dashboard: documentos ---
    [
        'path' => 'dashboard/reviewDocuments',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'reviewDocuments',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:documents.review'],
    ],
    [
        'path' => 'dashboard/approveDocument/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'approveDocument',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:documents.review'],
    ],
    [
        'path' => 'dashboard/rejectDocument/{id}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'rejectDocument',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:documents.review'],
    ],
    [
        'path' => 'dashboard/submitAccountDocument',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'submitAccountDocument',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/resubmitDocument/{documentId}',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'resubmitDocument',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],

    // --- Dashboard: perfil e conta (ControllerDashboardProfile) ---
    [
        'path' => 'profile/update',
        'controller' => 'ControllerDashboardProfile',
        'action' => 'update',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/becomeAffiliate',
        'controller' => 'ControllerDashboardProfile',
        'action' => 'becomeAffiliate',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],

    // --- Dashboard: subscrições (ControllerDashboardSubscriptions) ---
    [
        'path' => 'dashboard/confirmSubscriptionCheckout',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'confirmSubscriptionCheckout',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/changeSubscription',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'changeSubscription',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'dashboard/adminSetSubscription',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'adminSetSubscription',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'dashboard/confirmAdminSubscriptionCheckout',
        'controller' => 'ControllerDashboardSubscriptions',
        'action' => 'confirmAdminSubscriptionCheckout',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],

    // --- Configurações (admin) ---
    [
        'path' => 'settings',
        'controller' => 'ControllerDashboardAdmin',
        'action' => 'settings',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],

    // --- Property: catálogo (GET) ---
    [
        'path' => 'properties',
        'controller' => 'ControllerPropertyCatalog',
        'action' => 'properties',
        'methods' => ['GET'],
    ],
    [
        'path' => 'featured',
        'controller' => 'ControllerPropertyCatalog',
        'action' => 'featured',
        'methods' => ['GET'],
    ],
    [
        'path' => 'property/create',
        'controller' => 'ControllerPropertyOwner',
        'action' => 'create',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'property/edit/{id}',
        'controller' => 'ControllerPropertyOwner',
        'action' => 'edit',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'property/getAffiliationTerms',
        'controller' => 'ControllerPropertyEngagement',
        'action' => 'getAffiliationTerms',
        'methods' => ['GET'],
    ],
    [
        'path' => 'property/agency',
        'controller' => 'ControllerPropertyCatalog',
        'action' => 'agency',
        'methods' => ['GET'],
    ],
    [
        'path' => 'property/agency/{agencyUserId}',
        'controller' => 'ControllerPropertyCatalog',
        'action' => 'agency',
        'methods' => ['GET'],
    ],
    [
        'path' => 'property/owner/{id}',
        'controller' => 'ControllerPropertyCatalog',
        'action' => 'owner',
        'methods' => ['GET'],
    ],

    // --- Payment: métodos (ControllerPaymentMethods) ---
    [
        'path' => 'payment_methods',
        'controller' => 'ControllerPaymentMethods',
        'action' => 'payment_methods',
        'methods' => ['GET'],
        'middleware' => ['auth', 'super_admin'],
    ],
    [
        'path' => 'payment_methods/toggleMethod/{id}',
        'controller' => 'ControllerPaymentMethods',
        'action' => 'toggleMethod',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'payment_methods/createMethod',
        'controller' => 'ControllerPaymentMethods',
        'action' => 'createMethod',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'payment_methods/updateMethod/{id}',
        'controller' => 'ControllerPaymentMethods',
        'action' => 'updateMethod',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'payment_methods/deleteMethod/{id}',
        'controller' => 'ControllerPaymentMethods',
        'action' => 'deleteMethod',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],

    // --- Payment: transações (ControllerPaymentTransactions) ---
    [
        'path' => 'payment_transactions',
        'controller' => 'ControllerPaymentTransactions',
        'action' => 'payment_transactions',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:payments.manage'],
    ],
    [
        'path' => 'payment_transactions/exportTransactionsCsv',
        'controller' => 'ControllerPaymentTransactions',
        'action' => 'exportTransactionsCsv',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:payments.manage'],
    ],
    [
        'path' => 'payment_transactions/exportTransactionsPdf',
        'controller' => 'ControllerPaymentTransactions',
        'action' => 'exportTransactionsPdf',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:payments.manage'],
    ],
    [
        'path' => 'payment_transactions/confirmTransaction/{id}',
        'controller' => 'ControllerPaymentTransactions',
        'action' => 'confirmTransaction',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'payment_transactions/cancelTransaction/{id}',
        'controller' => 'ControllerPaymentTransactions',
        'action' => 'cancelTransaction',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'payment_transactions/rejectTransaction/{id}',
        'controller' => 'ControllerPaymentTransactions',
        'action' => 'rejectTransaction',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],

    // --- Payment: canais (ControllerPaymentChannels) ---
    [
        'path' => 'payment_channels',
        'controller' => 'ControllerPaymentChannels',
        'action' => 'payment_channels',
        'methods' => ['GET'],
        'middleware' => ['auth', 'super_admin'],
    ],
    [
        'path' => 'payment_channels/createChannel',
        'controller' => 'ControllerPaymentChannels',
        'action' => 'createChannel',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'payment_channels/updateChannel/{id}',
        'controller' => 'ControllerPaymentChannels',
        'action' => 'updateChannel',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'payment_channels/setDefaultChannel/{id}',
        'controller' => 'ControllerPaymentChannels',
        'action' => 'setDefaultChannel',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],
    [
        'path' => 'payment_channels/deactivateChannel/{id}',
        'controller' => 'ControllerPaymentChannels',
        'action' => 'deactivateChannel',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'super_admin'],
    ],

    // --- Property moderation (ControllerPropertyModeration) ---
    [
        'path' => 'property/moderate',
        'controller' => 'ControllerPropertyModeration',
        'action' => 'moderate',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:properties.moderate'],
    ],
    [
        'path' => 'property/approve/{id}',
        'controller' => 'ControllerPropertyModeration',
        'action' => 'approve',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:properties.moderate'],
    ],
    [
        'path' => 'property/reject/{id}',
        'controller' => 'ControllerPropertyModeration',
        'action' => 'reject',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:properties.moderate'],
    ],
    [
        'path' => 'property/startAnalysis/{id}',
        'controller' => 'ControllerPropertyModeration',
        'action' => 'startAnalysis',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:properties.moderate'],
    ],
    [
        'path' => 'property/approveBoost/{id}',
        'controller' => 'ControllerPropertyModeration',
        'action' => 'approveBoost',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'property/rejectBoost/{id}',
        'controller' => 'ControllerPropertyModeration',
        'action' => 'rejectBoost',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf', 'can:payments.manage'],
    ],
    [
        'path' => 'property/store',
        'controller' => 'ControllerPropertyOwner',
        'action' => 'store',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'property/update/{id}',
        'controller' => 'ControllerPropertyOwner',
        'action' => 'update',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'property/favorite/{id}',
        'controller' => 'ControllerPropertyEngagement',
        'action' => 'favorite',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'property/unfavorite/{id}',
        'controller' => 'ControllerPropertyEngagement',
        'action' => 'unfavorite',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'property/affiliateRequest/{id}',
        'controller' => 'ControllerPropertyEngagement',
        'action' => 'affiliateRequest',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'property/setStatus/{id}',
        'controller' => 'ControllerPropertyOwner',
        'action' => 'setStatus',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'property/requestBoost/{id}',
        'controller' => 'ControllerPropertyOwner',
        'action' => 'requestBoost',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'property/{id}',
        'controller' => 'ControllerPropertyCatalog',
        'action' => 'show',
        'methods' => ['GET'],
    ],

    // --- Requests (ControllerRequest*) ---
    [
        'path' => 'request',
        'controller' => 'ControllerRequestIntake',
        'action' => 'store',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/updateStatus/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'updateStatus',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/cancel/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'cancel',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/confirmClosing/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'confirmClosing',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/contestClosing/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'contestClosing',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/confirmPaymentReceipt/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'confirmPaymentReceipt',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/contestPayment/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'contestPayment',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/openDispute/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'openDispute',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/sendMessage/{id}',
        'controller' => 'ControllerRequestChat',
        'action' => 'sendMessage',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/approveAffiliate/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'approveAffiliate',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'request/rejectAffiliate/{id}',
        'controller' => 'ControllerRequestWorkflow',
        'action' => 'rejectAffiliate',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],

    // --- Notification inbox (ControllerNotification*) ---
    [
        'path' => 'notification/inbox',
        'controller' => 'ControllerNotificationInbox',
        'action' => 'inbox',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'notification/archive',
        'controller' => 'ControllerNotificationInbox',
        'action' => 'archive',
        'methods' => ['GET'],
        'middleware' => ['auth'],
    ],
    [
        'path' => 'notification/mark_as_read',
        'controller' => 'ControllerNotificationActions',
        'action' => 'markAsRead',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'notification/mark_all_as_read',
        'controller' => 'ControllerNotificationActions',
        'action' => 'markAllAsRead',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'notification/markAllAsRead',
        'controller' => 'ControllerNotificationActions',
        'action' => 'markAllAsRead',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'notification/archiveItem',
        'controller' => 'ControllerNotificationActions',
        'action' => 'archiveItem',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'notification/archiveAll',
        'controller' => 'ControllerNotificationActions',
        'action' => 'archiveAll',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'notification/unarchive',
        'controller' => 'ControllerNotificationActions',
        'action' => 'unarchive',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],
    [
        'path' => 'notification/delete',
        'controller' => 'ControllerNotificationActions',
        'action' => 'delete',
        'methods' => ['POST'],
        'middleware' => ['auth', 'csrf'],
    ],

    // --- Legacy aliases (URLs antigas / atalhos de primeiro segmento) ---
    [
        'path' => 'moderate',
        'controller' => 'ControllerPropertyModeration',
        'action' => 'moderate',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:properties.moderate'],
    ],
    [
        'path' => 'agency/{agencyUserId}',
        'controller' => 'ControllerPropertyCatalog',
        'action' => 'agency',
        'methods' => ['GET'],
    ],
    [
        'path' => 'moderate_users',
        'controller' => 'ControllerDashboardModeration',
        'action' => 'moderateUsers',
        'methods' => ['GET'],
        'middleware' => ['auth', 'can:users.review'],
    ],
    [
        'path' => 'api/v1/{subPath}',
        'controller' => 'ControllerApiV1',
        'action' => 'v1',
        'methods' => ['GET', 'POST', 'DELETE'],
    ],
];
